version: "2"
checks:
  method-count:
    config:
      threshold: 20
  file-lines:
    config:
      threshold: 250
exclude_patterns:
  - "**/*"  # Exclude all files initially
  - "!src/scripts/main/public/js/**/*"  # Explicitly include your desired directory